### ISSUE TITLE
【依頼】フリマアプリ挙動確認

### ISSUE THREAD

**Issue by takumi-murakami** [takumi-murakami/furima-30926#9]
以下ご確認お願いいたします。

# 自身のフリマアプリのURL (本番環境(Heroku)のURL)
https://furima-30926.herokuapp.com/

# Basic認証のIDとパスワード 
ID：admin
pass：murakami30926

# 出品者用のメールアドレスとパスワード (本番環境にて商品出品しているユーザーの情報)
メールアドレス：furima@f.com
pass：furima111
# 購入者用のメールアドレスとパスワード (上記とは異なる、本番環境で使用可能なユーザーの情報)
メールアドレス：murakami@f.com
pass：murakami111

# 購入用カードの番号・期限・セキュリティコード (PAY.JPのテストカード情報)
番号：4242424242424242
期限：month→3  year→23
セキュリティコード：123

**Comment by tech-taro** [comment]
takumi-murakamiさん、ご提出ありがとうございます！
挙動確認させて頂いたところ、以下の不備が見受けられましたので修正をお願いします！

[修正箇所]
商品購入機能の確認
・クレジットカード決済ができる
→ご提示頂いたクレジットカード情報を用いても「Token can't be blank」というエラーメッセージが表示され購入ができないので、修正をお願いします。

・エラーハンドリングができていること（適切では無い値が入力された場合、情報は保存されず、エラーメッセージを出力させる）
→郵便番号記入欄ですが、ハイフンがない時と郵便番号の文字数が不適切のときのエラーメッセージが同じなので、どちらの記入ミスかわかるように修正をお願いします。

修正し次第、以下のprotospace完了報告フォームを再度提出お願いします！
※新しいissueを作っていただく必要はありません
https://forms.gle/ZdLeprTTWhMA8aZA7

**Comment by takumi-murakami** [comment]
恐れ入ります。
以下を修正いたしましたので再度挙動の確認をお願いいたします。

> →ご提示頂いたクレジットカード情報を用いても「Token can't be blank」というエラーメッセージが表示され購入ができないので、修正をお願いします。

本番環境の公開鍵が設定されていなかったため修正いたしました。


> →郵便番号記入欄ですが、ハイフンがない時と郵便番号の文字数が不適切のときのエラーメッセージが同じなので、どちらの記入ミスかわかるように修正をお願いします。

バリデーションを変更し修正いたしました。
`with_options format: { with: /\A\d{3}[-]\d{4}\z/ } do  
      validates :postal_code, length: { is: 8 } 
    end`
https://gyazo.com/6c2319f665c6524dae99237b41002970

**Comment by tech-taro** [comment]
takumi-murakamiさん、ご提出ありがとうございます！
挙動確認させて頂いたところ、以下の不備が見受けられましたので修正をお願いします！

[修正箇所]
誤った提出フォームをご案内してしまい、大変申し訳ございません。
こちらは最終課題ですので、大変お手数ですが下記の最終課題提出フォームから再提出をお願い致します

修正し次第、以下の最終課題完了報告フォームを再度提出お願いします！
※新しいissueを作っていただく必要はありません
https://forms.gle/dYuR1wjeHepbEhU7A

**Comment by tech-taro** [comment]
takumi-murakami、ご提出ありがとうございます！
挙動確認させて頂きましたが、完成要件は全く問題ございませんでしたのでLGTMとさせて頂きます🎉
おめでとうございます！

必須ではありませんが、余裕があればこちらも修正し、よりクオリティの高いアプリケーションにしていただきたく存じます。（提出はしなくて大丈夫です。）
・商品削除機能の確認
購入済みの商品を削除しようとするとエラーになる

※確認したのは必須機能のみで追加実装した機能については確認していません。
そのため追加機能を実装している場合は、正しく想定通りの挙動であるかご自身で再度確認をお願いいたします。

**Comment by takumi-murakami** [comment]
ご確認いただきありがとうございました！

> 必須ではありませんが、余裕があればこちらも修正し、よりクオリティの高いアプリケーションにしていただきたく存じます。（提出はしなくて大丈夫です。）
・商品削除機能の確認
購入済みの商品を削除しようとするとエラーになる

上記修正いたします。
追加実装やオリジナルアプリの挙動確認は自らで行います。

よろしくお願いいたします。
